// flow-typed signature: 95347671fcf465e3ef1a6c3b7f4a999e
// flow-typed version: <<STUB>>/wepback_v^1.0.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wepback'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'wepback' {
  declare module.exports: any;
}
