// flow-typed signature: 33447ffcf534dd009e2aa8fbafef42db
// flow-typed version: <<STUB>>/@reggi/react-navigation-views_v0.1.3/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@reggi/react-navigation-views'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@reggi/react-navigation-views' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@reggi/react-navigation-views/Examples/StackExample/StackExample' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/Examples/TabEx/TabExample' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/Examples/TabExample/TabExample' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/lib/__tests__/NavigationScenesReducer-test' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/lib/__tests__/NavigationStateUtils-test' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/lib/CustomComponents/NavigationCard' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/lib/CustomComponents/NavigationCardStack' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/lib/CustomComponents/NavigationCardStackPanResponder' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/lib/CustomComponents/NavigationCardStackStyleInterpolator' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/lib/CustomComponents/NavigationHeader' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/lib/CustomComponents/NavigationHeaderBackButton' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/lib/CustomComponents/NavigationHeaderStyleInterpolator' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/lib/CustomComponents/NavigationHeaderTitle' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/lib/CustomComponents/NavigationPagerPanResponder' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/lib/CustomComponents/NavigationPagerStyleInterpolator' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/lib/CustomComponents/NavigationPointerEventsContainer' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/lib/NavigationAbstractPanResponder' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/lib/NavigationAnimatedValueSubscription' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/lib/NavigationPropTypes' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/lib/NavigationScenesReducer' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/lib/NavigationStateUtils' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/lib/NavigationTransitioner' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/lib/NavigationTypeDefinition' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/lib/NavigationViews' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/src/__tests__/NavigationScenesReducer-test' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/src/__tests__/NavigationStateUtils-test' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/src/CustomComponents/NavigationCard' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/src/CustomComponents/NavigationCardStack' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/src/CustomComponents/NavigationCardStackPanResponder' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/src/CustomComponents/NavigationCardStackStyleInterpolator' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/src/CustomComponents/NavigationHeader' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/src/CustomComponents/NavigationHeaderBackButton' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/src/CustomComponents/NavigationHeaderStyleInterpolator' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/src/CustomComponents/NavigationHeaderTitle' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/src/CustomComponents/NavigationPagerPanResponder' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/src/CustomComponents/NavigationPagerStyleInterpolator' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/src/CustomComponents/NavigationPointerEventsContainer' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/src/NavigationAbstractPanResponder' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/src/NavigationAnimatedValueSubscription' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/src/NavigationPropTypes' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/src/NavigationScenesReducer' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/src/NavigationStateUtils' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/src/NavigationTransitioner' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/src/NavigationTypeDefinition' {
  declare module.exports: any;
}

declare module '@reggi/react-navigation-views/src/NavigationViews' {
  declare module.exports: any;
}

// Filename aliases
declare module '@reggi/react-navigation-views/Examples/StackExample/StackExample.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/Examples/StackExample/StackExample'>;
}
declare module '@reggi/react-navigation-views/Examples/TabEx/TabExample.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/Examples/TabEx/TabExample'>;
}
declare module '@reggi/react-navigation-views/Examples/TabExample/TabExample.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/Examples/TabExample/TabExample'>;
}
declare module '@reggi/react-navigation-views/lib/__tests__/NavigationScenesReducer-test.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/lib/__tests__/NavigationScenesReducer-test'>;
}
declare module '@reggi/react-navigation-views/lib/__tests__/NavigationStateUtils-test.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/lib/__tests__/NavigationStateUtils-test'>;
}
declare module '@reggi/react-navigation-views/lib/CustomComponents/NavigationCard.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/lib/CustomComponents/NavigationCard'>;
}
declare module '@reggi/react-navigation-views/lib/CustomComponents/NavigationCardStack.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/lib/CustomComponents/NavigationCardStack'>;
}
declare module '@reggi/react-navigation-views/lib/CustomComponents/NavigationCardStackPanResponder.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/lib/CustomComponents/NavigationCardStackPanResponder'>;
}
declare module '@reggi/react-navigation-views/lib/CustomComponents/NavigationCardStackStyleInterpolator.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/lib/CustomComponents/NavigationCardStackStyleInterpolator'>;
}
declare module '@reggi/react-navigation-views/lib/CustomComponents/NavigationHeader.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/lib/CustomComponents/NavigationHeader'>;
}
declare module '@reggi/react-navigation-views/lib/CustomComponents/NavigationHeaderBackButton.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/lib/CustomComponents/NavigationHeaderBackButton'>;
}
declare module '@reggi/react-navigation-views/lib/CustomComponents/NavigationHeaderStyleInterpolator.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/lib/CustomComponents/NavigationHeaderStyleInterpolator'>;
}
declare module '@reggi/react-navigation-views/lib/CustomComponents/NavigationHeaderTitle.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/lib/CustomComponents/NavigationHeaderTitle'>;
}
declare module '@reggi/react-navigation-views/lib/CustomComponents/NavigationPagerPanResponder.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/lib/CustomComponents/NavigationPagerPanResponder'>;
}
declare module '@reggi/react-navigation-views/lib/CustomComponents/NavigationPagerStyleInterpolator.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/lib/CustomComponents/NavigationPagerStyleInterpolator'>;
}
declare module '@reggi/react-navigation-views/lib/CustomComponents/NavigationPointerEventsContainer.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/lib/CustomComponents/NavigationPointerEventsContainer'>;
}
declare module '@reggi/react-navigation-views/lib/NavigationAbstractPanResponder.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/lib/NavigationAbstractPanResponder'>;
}
declare module '@reggi/react-navigation-views/lib/NavigationAnimatedValueSubscription.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/lib/NavigationAnimatedValueSubscription'>;
}
declare module '@reggi/react-navigation-views/lib/NavigationPropTypes.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/lib/NavigationPropTypes'>;
}
declare module '@reggi/react-navigation-views/lib/NavigationScenesReducer.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/lib/NavigationScenesReducer'>;
}
declare module '@reggi/react-navigation-views/lib/NavigationStateUtils.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/lib/NavigationStateUtils'>;
}
declare module '@reggi/react-navigation-views/lib/NavigationTransitioner.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/lib/NavigationTransitioner'>;
}
declare module '@reggi/react-navigation-views/lib/NavigationTypeDefinition.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/lib/NavigationTypeDefinition'>;
}
declare module '@reggi/react-navigation-views/lib/NavigationViews.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/lib/NavigationViews'>;
}
declare module '@reggi/react-navigation-views/src/__tests__/NavigationScenesReducer-test.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/src/__tests__/NavigationScenesReducer-test'>;
}
declare module '@reggi/react-navigation-views/src/__tests__/NavigationStateUtils-test.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/src/__tests__/NavigationStateUtils-test'>;
}
declare module '@reggi/react-navigation-views/src/CustomComponents/NavigationCard.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/src/CustomComponents/NavigationCard'>;
}
declare module '@reggi/react-navigation-views/src/CustomComponents/NavigationCardStack.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/src/CustomComponents/NavigationCardStack'>;
}
declare module '@reggi/react-navigation-views/src/CustomComponents/NavigationCardStackPanResponder.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/src/CustomComponents/NavigationCardStackPanResponder'>;
}
declare module '@reggi/react-navigation-views/src/CustomComponents/NavigationCardStackStyleInterpolator.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/src/CustomComponents/NavigationCardStackStyleInterpolator'>;
}
declare module '@reggi/react-navigation-views/src/CustomComponents/NavigationHeader.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/src/CustomComponents/NavigationHeader'>;
}
declare module '@reggi/react-navigation-views/src/CustomComponents/NavigationHeaderBackButton.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/src/CustomComponents/NavigationHeaderBackButton'>;
}
declare module '@reggi/react-navigation-views/src/CustomComponents/NavigationHeaderStyleInterpolator.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/src/CustomComponents/NavigationHeaderStyleInterpolator'>;
}
declare module '@reggi/react-navigation-views/src/CustomComponents/NavigationHeaderTitle.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/src/CustomComponents/NavigationHeaderTitle'>;
}
declare module '@reggi/react-navigation-views/src/CustomComponents/NavigationPagerPanResponder.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/src/CustomComponents/NavigationPagerPanResponder'>;
}
declare module '@reggi/react-navigation-views/src/CustomComponents/NavigationPagerStyleInterpolator.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/src/CustomComponents/NavigationPagerStyleInterpolator'>;
}
declare module '@reggi/react-navigation-views/src/CustomComponents/NavigationPointerEventsContainer.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/src/CustomComponents/NavigationPointerEventsContainer'>;
}
declare module '@reggi/react-navigation-views/src/NavigationAbstractPanResponder.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/src/NavigationAbstractPanResponder'>;
}
declare module '@reggi/react-navigation-views/src/NavigationAnimatedValueSubscription.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/src/NavigationAnimatedValueSubscription'>;
}
declare module '@reggi/react-navigation-views/src/NavigationPropTypes.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/src/NavigationPropTypes'>;
}
declare module '@reggi/react-navigation-views/src/NavigationScenesReducer.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/src/NavigationScenesReducer'>;
}
declare module '@reggi/react-navigation-views/src/NavigationStateUtils.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/src/NavigationStateUtils'>;
}
declare module '@reggi/react-navigation-views/src/NavigationTransitioner.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/src/NavigationTransitioner'>;
}
declare module '@reggi/react-navigation-views/src/NavigationTypeDefinition.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/src/NavigationTypeDefinition'>;
}
declare module '@reggi/react-navigation-views/src/NavigationViews.js' {
  declare module.exports: $Exports<'@reggi/react-navigation-views/src/NavigationViews'>;
}
